### ISSUE TITLE
Dataset inquiry

### ISSUE THREAD

**Issue by Alan-Heoooh** [irom-lab/dppo#1]
Hi,

It's impressive to see the shocking results of DPPO. About the dataset, I wonder that is only one demonstration of furniture-bench availiable in Google Drive right now? Can I use the demonstrations from the orginal furniture-bench repo [(Google Drive)](https://drive.google.com/drive/folders/1j59vFmgBsatu1PZK52HWX_9o5BCh_XDt) to train the model?

Thanks

**Comment by allenzren** [comment]
Hi, thanks for the interest! We collected our own demonstrations in simulation (see App. D7 of our paper), and we used the ground-truth object states as part of the policy input (plus the robot state, no pixels)

I just looked at the original demonstrations from furniture-bench and I didn't see the object states from the collected data (only the robot state), correct me if I am wrong. If there is both states then I think we can convert the original data to our format easily and pre-train the policy.

Fine-tuning pixel policy with Furniture-Bench might be challenging though as the simulation speed might not be optimized. I am not entirely sure but @ankile might have more ideas.

**Comment by ankile** [comment]
Hi @Alan-Heoooh !

Yes, as Allen said, we collected our own demonstration data by hand with a Spacemouse in simulation, recording both robot states and ground-truth object states. We are going to make all our demo data public quite soon. I can let you know when it's ready!

**Comment by allenzren** [comment]
@Alan-Heoooh Just to be clear, the data we collected is available right now and you can use it to pre-train the policy. I think @ankile plans to have a more formal release of all the demo data from his work [robust rearragement](https://github.com/ankile/robust-rearrangement)

**Comment by Alan-Heoooh** [comment]
Hi, @allenzren @ankile ,

Thank you for your kind reply. But I still wonder that is _train.pkl_ in [this folder](https://drive.google.com/drive/folders/1v4LG2D1fS8id5hqE7Jjt7MYNFUEBNyh4) contains all the training demonstrations for pretrain? Also, I didn't see the updated data for furniture-bench. Could you please post a link here? 

Thanks!

**Comment by allenzren** [comment]
@Alan-Heoooh Yes _train.pkl_ contains all the training demos (50 trajectories, you can see the details in the log file) we used for pre-training in the DPPO paper. I am not sure if @ankile has more demos that will be released for a particular task, but even so those are used only in the robust rearrangement paper, not DPPO.

What do you mean by "updated data"?

**Comment by Alan-Heoooh** [comment]
Got it. Thanks for your reply!

**Comment by allenzren** [comment]
Btw I updated the training data and I replaced pkl with npz files, which is much smaller in size.
