### ISSUE TITLE
Small bugs in eval agents

### ISSUE THREAD

**Issue by acl21** [irom-lab/dppo#11]
Hi @allenzren, I just wanted to bring to your notice that `self.itr` appears in eval agents without prior initialization. 

https://github.com/irom-lab/dppo/blob/e0842e71dc62cc0079f737672a5ab7bd49abe9e3/agent/eval/eval_diffusion_agent.py#L31
https://github.com/irom-lab/dppo/blob/e0842e71dc62cc0079f737672a5ab7bd49abe9e3/agent/eval/eval_diffusion_img_agent.py#L35
https://github.com/irom-lab/dppo/blob/e0842e71dc62cc0079f737672a5ab7bd49abe9e3/agent/eval/eval_gaussian_agent.py#L31
https://github.com/irom-lab/dppo/blob/e0842e71dc62cc0079f737672a5ab7bd49abe9e3/agent/eval/eval_gaussian_img_agent.py#L35

**Comment by allenzren** [comment]
oops thank you! it is fixed now.
