### ISSUE TITLE
Possible bug in StitchedSequenceDataset

### ISSUE THREAD

**Issue by Yifei-Y** [irom-lab/dppo#6]
Hi @allenzren, first, thank you for the excellent work and for making such a high-quality codebase.

While working with the code, I came across a potential issue in [agent/dataset/sequence.py](https://github.com/irom-lab/dppo/blob/main/agent/dataset/sequence.py) on line 94 and 103. Perhaps `max` should be used instead of `min`. All of your experiments used cond_steps=1, so this bug hasn't had any impact. However, if cond_steps > 1, it could potentially cause issues.

I wanted to bring this to your attention in case it's an oversight or if there’s some aspect I might be misunderstanding. I would love to hear your thoughts on this.

Thanks!

**Comment by allenzren** [comment]
Ah that is right, thanks for noticing it and letting me know! It is fixed now in ef5b14f820080e2330915c1bc83b8e33ac622533. I will close the issue for now
